# https://github.com/pytorch/vision/tree/main/references/classification
--- # config.yaml

devices: gpu:0,1,2,3
seed: 0
amp: true
save_per_epoch: 1

#
# Dataset
#
num_classes: 1000
batch_size: 64
num_workers: 8
pin_memory: true

#
# Regularization
#
# label_smoothing: 0.1
# mixup_alpha: 0.8
# cutmix_alpha: 1.0
# gradient_clip_val: 5.0

#
# Training hyperparameters
#
epochs: 300
init_lr: 1.e-3

optimizer: AdamW
optimizer_cfg:
  weight_decay: 5.e-2

lr_scheduler: CosineAnnealingLR
lr_scheduler_cfg:
  eta_min: 1.e-5

warmup_lr_scheduler: LinearLR
warmup_lr_scheduler_cfg:
  start_factor: 1.e-2
  total_iters: 20

criterion: CrossEntropyLoss

... # end